=== B3bang/PKCK/Zadanie 1/zad1.dtd
<!ENTITY % kalendarz "dzień (01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31) #REQUIRED
	miesiąc (stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia) #REQUIRED
	rok CDATA #REQUIRED">

<!ELEMENT Płytoteka (Informacje, Gatunki-muzyki+)>

<!ELEMENT Informacje (Nazwa, Autor, Ostatnia-modyfikacja)>

<!ELEMENT Nazwa (#PCDATA)>

<!ELEMENT Autor (Imię-i-nazwisko)>
<!ATTLIST Autor id ID #REQUIRED>
<!ELEMENT Imię-i-nazwisko (#PCDATA)>

<!ELEMENT Ostatnia-modyfikacja EMPTY>
<!ATTLIST Ostatnia-modyfikacja
	%kalendarz;
        Autor CDATA #REQUIRED>
	
<!ELEMENT Gatunki-muzyki (Nazwa, Albumy)>
<!ELEMENT Albumy (Album*)>

<!ELEMENT Album (Zespół,Data-wydania,Nagradzana,Cena+)>
<!ATTLIST Album Nazwa-albumu CDATA #REQUIRED>
<!ELEMENT Zespół (Członek*)>
<!ATTLIST Zespół Wykonawca CDATA #REQUIRED>
<!ELEMENT Członek (Imię-i-nazwisko)>
<!ELEMENT Data-wydania (#PCDATA)>
<!ATTLIST Data-wydania %kalendarz;>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena waluta (PLN|USD) #REQUIRED>
<!ELEMENT Nagradzana (#PCDATA)>
<!ATTLIST Nagradzana nagroda (PlatynowaPłyta | ZłotaPłyta | Brak) "Brak">

=== B3bang/PKCK/Zadanie 1/zad1.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type='text/css' href='zad1.css'?>
<!DOCTYPE płytoteka SYSTEM 'zad1.dtd'>

<Płytoteka>
	<Informacje>
        <Nazwa>Płytoteka</Nazwa>
        <Autor id="_207230">
            <Imię-i-nazwisko>Bartosz Goss</Imię-i-nazwisko>
        </Autor>
        <Ostatnia-modyfikacja dzień="28" miesiąc="marca" rok="2019" Autor="_207230"/>
    </Informacje>
  <Gatunki-muzyki>
    <Nazwa>METAL</Nazwa>
    <Albumy>
      <Album Nazwa-albumu="Kill'em All">
        <Zespół Wykonawca="Metallica">
          <Członek>
            <Imię-i-nazwisko>James Hetfield</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Kirk Hammet</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Cliff Burton</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Lars Ulrich</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Jason Newsted</Imię-i-nazwisko>
          </Członek>
        </Zespół>
	<Data-wydania dzień="25" miesiąc="lipca" rok="1983"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">28.99</Cena>
		<Cena waluta="USD">9.99</Cena>
      </Album>
      <Album Nazwa-albumu="Ride the Lightning">
        <Zespół Wykonawca="Metallica">
          <Członek>
            <Imię-i-nazwisko>James Hetfield</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Kirk Hammet</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Cliff Burton</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Lars Ulrich</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Jason Newsted</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="27" miesiąc="lipca" rok="1984"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">30.99</Cena>
		<Cena waluta="USD">9.99</Cena>
      </Album>
      <Album Nazwa-albumu="Master of Puppets">
        <Zespół Wykonawca="Metallica">
          <Członek>
            <Imię-i-nazwisko>James Hetfield</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Kirk Hammet</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Cliff Burton</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Lars Ulrich</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Jason Newsted</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="03" miesiąc="marca" rok="1986"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">30.99</Cena>
		<Cena waluta="USD">9.99</Cena>
      </Album>
      <Album Nazwa-albumu="Countdown to Extinction">
        <Zespół Wykonawca="Megadeth">
          <Członek>
            <Imię-i-nazwisko>Dave Mustaine</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>David Ellefson</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Marty Friedman</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Nick Menza</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="14" miesiąc="lipca" rok="1992"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">35.99</Cena>
		<Cena waluta="USD">9.99</Cena>
      </Album>
      <Album Nazwa-albumu="Rust in Peace">
        <Zespół Wykonawca="Megadeth">
          <Członek>
            <Imię-i-nazwisko>Dave Mustaine</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>David Ellefson</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Marty Friedman</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Nick Menza</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="24" miesiąc="września" rok="1990"/>
        <Nagradzana nagroda="PlatynowaPłyta"></Nagradzana>
		<Cena waluta="PLN">24.99</Cena>
		<Cena waluta="USD">8.99</Cena>
      </Album>
      <Album Nazwa-albumu="Paranoid">
        <Zespół Wykonawca="Black Sabbath">
          <Członek>
            <Imię-i-nazwisko>Ozzy Osbourne</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Tony Iommi</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Geezer Butler</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="18" miesiąc="września" rok="1970"/>
        <Nagradzana nagroda="ZłotaPłyta"/>
		<Cena waluta="PLN">27.99</Cena>
		<Cena waluta="USD">8.99</Cena>
      </Album>
      <Album Nazwa-albumu="Masters of Reality">
        <Zespół Wykonawca="Black Sabbath">
          <Członek>
            <Imię-i-nazwisko>Ozzy Osbourne</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Tony Iommi</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Geezer Butler</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="21" miesiąc="lipca" rok="1971"/>
        <Nagradzana nagroda="ZłotaPłyta"/>
		<Cena waluta="PLN">25.99</Cena>
		<Cena waluta="USD">8.99</Cena>
      </Album>
    </Albumy>
  </Gatunki-muzyki>
  <Gatunki-muzyki>
    <Nazwa>POP</Nazwa>
    <Albumy>
      <Album Nazwa-albumu="1989">
        <Zespół Wykonawca="Taylor Swift" />
        <Data-wydania dzień="27" miesiąc="października" rok="2014"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">23.99</Cena>
		<Cena waluta="USD">8.99</Cena>
      </Album>
      <Album Nazwa-albumu="Thriller">
        <Zespół Wykonawca="Michael Jackson" />
        <Data-wydania dzień="30" miesiąc="listopada" rok="1982"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>   
		<Cena waluta="PLN">29.98</Cena>	
		<Cena waluta="USD">9.70</Cena>		
      </Album>
      <Album Nazwa-albumu="Bad">
        <Zespół Wykonawca="Michael Jackson" />
		<Data-wydania dzień="31" miesiąc="sierpnia" rok="1987"/>
        <Nagradzana nagroda="PlatynowaPłyta"/>
		<Cena waluta="PLN">33.70</Cena>
		<Cena waluta="USD">11.70</Cena>
      </Album>
    </Albumy>
  </Gatunki-muzyki>
  <Gatunki-muzyki>
    <Nazwa>ROCK</Nazwa>
    <Albumy>
      <Album Nazwa-albumu="Foo Fighters">
        <Zespół Wykonawca="Foo Fighters">
          <Członek>
            <Imię-i-nazwisko>Dave Grohl</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Nate Mendel</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Pat Smear</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Taylor Hawkins</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Chris Shiflett</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="07" miesiąc="lipca" rok="1995"/>
        <Nagradzana nagroda="ZłotaPłyta"/> 
		<Cena waluta="PLN">30.99</Cena>
		<Cena waluta="USD">10.99</Cena>
      </Album>
      <Album Nazwa-albumu="Sonic Highways">
        <Zespół Wykonawca="Foo Fighters">
          <Członek>
            <Imię-i-nazwisko>Dave Grohl</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Nate Mendel</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Pat Smear</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Taylor Hawkins</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Chris Shiflett</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="10" miesiąc="listopada" rok="2014"/>
        <Nagradzana nagroda="ZłotaPłyta"/>
		<Cena waluta="PLN">32.99</Cena>
		<Cena waluta="USD">12.99</Cena>
      </Album>
      <Album Nazwa-albumu="Concrete and Gold">
        <Zespół Wykonawca="Foo Fighters">
          <Członek>
            <Imię-i-nazwisko>Dave Grohl</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Nate Mendel</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Pat Smear</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Taylor Hawkins</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Chris Shiflett</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="15" miesiąc="września" rok="2017"/>
        <Nagradzana nagroda="ZłotaPłyta"/>   
		<Cena waluta="PLN">31.99</Cena>
		<Cena waluta="USD">11.99</Cena>
      </Album>
      <Album Nazwa-albumu="Queen">
        <Zespół Wykonawca="Queen">
          <Członek>
            <Imię-i-nazwisko>Freddie Mercury</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Roger Taylor</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Brian May</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>John Deacon</Imię-i-nazwisko>
          </Członek>
        </Zespół>
        <Data-wydania dzień="13" miesiąc="lipca" rok="1973"/>
        <Nagradzana nagroda="Brak"/>
		<Cena waluta="PLN">29.99</Cena>
		<Cena waluta="USD">9.99</Cena>
      </Album>
      <Album Nazwa-albumu="The Game">
        <Zespół Wykonawca="Queen">
          <Członek>
            <Imię-i-nazwisko>Freddie Mercury</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Roger Taylor</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>Brian May</Imię-i-nazwisko>
          </Członek>
          <Członek>
            <Imię-i-nazwisko>John Deacon</Imię-i-nazwisko>
