=== B3bang/PKCK/Zadanie 5/XML/zad2.xsd
<?xml version='1.0' encoding='utf-8'?>
<xs:schema xmlns="http://tempuri.org/zad1" 
elementFormDefault="qualified" 
xmlns:mojNamespace="https://www.github.com/B3bang"
targetNamespace="https://www.github.com/B3bang"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:attributeGroup name="daty">
		<xs:attribute name="dzień">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="31"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="miesiąc">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="stycznia" />
					<xs:enumeration value="lutego" />
					<xs:enumeration value="marca" />
					<xs:enumeration value="kwietnia" />
					<xs:enumeration value="maja" />
					<xs:enumeration value="czerwca" />
					<xs:enumeration value="lipca" />
					<xs:enumeration value="sierpnia" />
					<xs:enumeration value="września" />
					<xs:enumeration value="października" />
					<xs:enumeration value="listopada" />
					<xs:enumeration value="grudnia" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>	
		<xs:attribute name="rok" type="xs:gYear"/>
	</xs:attributeGroup>

	<xs:element name="Płytoteka" type="mojNamespace:Typ-Płytoteka"/>

	<xs:complexType name="Typ-Płytoteka">
      <xs:sequence>
        <xs:element name="Informacje" type="mojNamespace:Typ-Informacje"/>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Gatunki-muzyki" type="mojNamespace:Typ-Gatunki-muzyki"/>
      </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Typ-Informacje">
      <xs:sequence>
        <xs:element name="Nazwa" type="xs:string"/>
        <xs:element name="Autorzy" type="mojNamespace:Typ-Autorzy"/>
        <xs:element name="Ostatnia-modyfikacja" type="mojNamespace:Typ-Ostatnia-modyfikacja"/>
      </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Typ-Autorzy">
		<xs:sequence>
			<xs:element name="Autor" type="mojNamespace:Typ-Autor" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Typ-Autor">
		<xs:sequence>
			<xs:element name="Imię-i-nazwisko" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="_{1}[0-9]{6}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
    </xs:complexType>

	<xs:complexType name="Typ-Ostatnia-modyfikacja">
			<xs:attributeGroup ref="mojNamespace:daty"/>
			<xs:attribute name="Autor" type="xs:IDREF"/>
	</xs:complexType>

	<xs:complexType name="Typ-Gatunki-muzyki">
		<xs:sequence>
			<xs:element name="Gatunek-muzyki" type="mojNamespace:Typ-Gatunek-muzyki" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Typ-Gatunek-muzyki">
		<xs:sequence>
			<xs:element name="Nazwa" type="xs:string"/>
			<xs:element name="Albumy" type="mojNamespace:Typ-Albumy"/>
		</xs:sequence>
	</xs:complexType>

    <xs:complexType name="Typ-Albumy">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Album" type="mojNamespace:Typ-Album"/>
      </xs:sequence>
    </xs:complexType>

    <xs:group name="Grupa-Album">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="Zespół" type="mojNamespace:Typ-Zespół" />
			<xs:element minOccurs="1" maxOccurs="1" name="Data-wydania" type="mojNamespace:Typ-Data-wydania" />
			<xs:element minOccurs="1" maxOccurs="1" name="Nagradzana" type="mojNamespace:Typ-Nagradzana"/>
			<xs:element minOccurs="1" maxOccurs="1" name="Ceny" type="mojNamespace:Typ-Ceny" />
      </xs:sequence>
	</xs:group>

	<xs:complexType name="Typ-Album">
      <xs:sequence>
        <xs:group ref="mojNamespace:Grupa-Album" />
      </xs:sequence>
      <xs:attribute name="Nazwa-albumu" type="xs:string" use="required" />
    </xs:complexType>
	<xs:complexType name="Typ-Zespół">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Członkowie" type="mojNamespace:Typ-Członkowie" />
		</xs:sequence>
		<xs:attribute name="Wykonawca" type="xs:string"/>
		<xs:attribute name="id" type="xs:ID"></xs:attribute>
		<xs:attribute name="refid" type="xs:IDREF"></xs:attribute>
    </xs:complexType>

   <xs:complexType name="Typ-Członkowie">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Członek" type="mojNamespace:Typ-Członek"/>
      </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Typ-Członek">
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" name="Imię-i-nazwisko" type="xs:string" />
      </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Typ-Data-wydania">
		<xs:attributeGroup ref="mojNamespace:daty"/>
    </xs:complexType>
	<xs:complexType name="Typ-Nagradzana">
		<xs:attribute default="Brak" name="nagroda">
            <xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="PlatynowaPłyta" />
					<xs:enumeration value="ZłotaPłyta" />
					<xs:enumeration value="Brak" />
				</xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

	<xs:simpleType name="CenaPoPrzecinku">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>

   <xs:complexType name="Typ-Ceny">
      <xs:sequence>
        <xs:element minOccurs="2" maxOccurs="2" name="Cena" type="mojNamespace:Typ-Cena"/>
      </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Typ-Cena">
		<xs:simpleContent>
			<xs:extension base="mojNamespace:CenaPoPrzecinku">
				<xs:attribute name="waluta">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="USD" />
							<xs:enumeration value="PLN" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== B3bang/PKCK/Zadanie 5/src/main/resources/zad2.xml
<?xml version='1.0' encoding='utf-8'?>
<Płytoteka zid="_0" xsd:schemaLocation="https://www.github.com/B3bang zad2.xsd" xmlns="https://www.github.com/B3bang" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance">
   <Informacje zid="_1">
      <Nazwa zid="_2">Płytoteka</Nazwa>
      <Autorzy zid="_3">
         <Autor zid="_4" id="_207230">
            <Imię-i-nazwisko zid="_5">Bartosz Goss</Imię-i-nazwisko>
         </Autor>
         <Autor zid="_6" id="_210203">
            <Imię-i-nazwisko zid="_7">Piotr Janicki</Imię-i-nazwisko>
         </Autor>
      </Autorzy>
      <Ostatnia-modyfikacja zid="_8" dzień="28" miesiąc="marca" rok="2019" Autor="_207230"/>
   </Informacje>
   <Gatunki-muzyki zid="_9">
      <Gatunek-muzyki zid="_10">
         <Nazwa zid="_11">METAL</Nazwa>
         <Albumy zid="_12">
            <Album zid="_13" Nazwa-albumu="Kill&apos;em All">
               <Zespół zid="_14" Wykonawca="Metallica">
                  <Członkowie zid="_15">
                     <Członek zid="_16">
                        <Imię-i-nazwisko zid="_17">James Hetfield</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_18">
                        <Imię-i-nazwisko zid="_19">Kirk Hammet</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_20">
                        <Imię-i-nazwisko zid="_21">Cliff Burton</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_22">
                        <Imię-i-nazwisko zid="_23">Lars Ulrich</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_24">
                        <Imię-i-nazwisko zid="_25">Jason Newsted</Imię-i-nazwisko>
                     </Członek>
                  </Członkowie>
               </Zespół>
               <Data-wydania zid="_26" dzień="25" miesiąc="lipca" rok="1983"/>
               <Nagradzana zid="_27" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_28">
                  <Cena zid="_29" waluta="PLN">28.99</Cena>
                  <Cena zid="_30" waluta="USD">9.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_31" Nazwa-albumu="Ride the Lightning">
               <Zespół refzid="_14"/>
               <Data-wydania zid="_32" dzień="27" miesiąc="lipca" rok="1984"/>
               <Nagradzana zid="_33" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_34">
                  <Cena zid="_35" waluta="PLN">30.99</Cena>
                  <Cena zid="_36" waluta="USD">9.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_37" Nazwa-albumu="Master of Puppets">
               <Zespół refzid="_14"/>
               <Data-wydania zid="_38" dzień="3" miesiąc="marca" rok="1986"/>
               <Nagradzana zid="_39" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_40">
                  <Cena zid="_41" waluta="PLN">30.99</Cena>
                  <Cena zid="_42" waluta="USD">9.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_43" Nazwa-albumu="Countdown to Extinction">
               <Zespół zid="_44" Wykonawca="Megadeth">
                  <Członkowie zid="_45">
                     <Członek zid="_46">
                        <Imię-i-nazwisko zid="_47">Dave Mustaine</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_48">
                        <Imię-i-nazwisko zid="_49">Davzid Ellefson</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_50">
                        <Imię-i-nazwisko zid="_51">Marty Friedman</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_52">
                        <Imię-i-nazwisko zid="_53">Nick Menza</Imię-i-nazwisko>
                     </Członek>
                  </Członkowie>
               </Zespół>
               <Data-wydania zid="_54" dzień="14" miesiąc="lipca" rok="1992"/>
               <Nagradzana zid="_55" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_56">
                  <Cena zid="_57" waluta="PLN">35.99</Cena>
                  <Cena zid="_58" waluta="USD">9.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_59" Nazwa-albumu="Rust in Peace">
               <Zespół refzid="_44"/>
               <Data-wydania zid="_60" dzień="24" miesiąc="września" rok="1990"/>
               <Nagradzana zid="_61" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_62">
                  <Cena zid="_63" waluta="PLN">24.99</Cena>
                  <Cena zid="_64" waluta="USD">8.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_65" Nazwa-albumu="Paranozid">
               <Zespół zid="_66" Wykonawca="Black Sabbath">
                  <Członkowie zid="_67">
                     <Członek zid="_68">
                        <Imię-i-nazwisko zid="_69">Ozzy Osbourne</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_70">
                        <Imię-i-nazwisko zid="_71">Tony Iommi</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_72">
                        <Imię-i-nazwisko zid="_73">Geezer Butler</Imię-i-nazwisko>
                     </Członek>
                  </Członkowie>
               </Zespół>
               <Data-wydania zid="_74" dzień="18" miesiąc="września" rok="1970"/>
               <Nagradzana zid="_75" nagroda="ZłotaPłyta"/>
               <Ceny zid="_76">
                  <Cena zid="_77" waluta="PLN">27.99</Cena>
                  <Cena zid="_78" waluta="USD">8.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_79" Nazwa-albumu="Masters of Reality">
               <Zespół refzid="_66"/>
               <Data-wydania zid="_80" dzień="21" miesiąc="lipca" rok="1971"/>
               <Nagradzana zid="_81" nagroda="ZłotaPłyta"/>
               <Ceny zid="_82">
                  <Cena zid="_83" waluta="PLN">25.99</Cena>
                  <Cena zid="_84" waluta="USD">8.99</Cena>
               </Ceny>
            </Album>
         </Albumy>
      </Gatunek-muzyki>
      <Gatunek-muzyki zid="_85">
         <Nazwa zid="_86">POP</Nazwa>
         <Albumy zid="_87">
            <Album zid="_88" Nazwa-albumu="1989">
               <Zespół zid="_89" Wykonawca="Taylor Swift"/>
               <Data-wydania zid="_90" dzień="27" miesiąc="października" rok="2014"/>
               <Nagradzana zid="_91" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_92">
                  <Cena zid="_93" waluta="PLN">23.99</Cena>
                  <Cena zid="_94" waluta="USD">8.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_95" Nazwa-albumu="Thriller">
               <Zespół zid="_96" Wykonawca="Michael Jackson"/>
               <Data-wydania zid="_97" dzień="30" miesiąc="listopada" rok="1982"/>
               <Nagradzana zid="_98" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_99">
                  <Cena zid="_100" waluta="PLN">29.98</Cena>
                  <Cena zid="_101" waluta="USD">9.7</Cena>
               </Ceny>
            </Album>
            <Album zid="_102" Nazwa-albumu="Bad">
               <Zespół refzid="_96"/>
               <Data-wydania zid="_103" dzień="31" miesiąc="sierpnia" rok="1987"/>
               <Nagradzana zid="_104" nagroda="PlatynowaPłyta"/>
               <Ceny zid="_105">
                  <Cena zid="_106" waluta="PLN">33.7</Cena>
                  <Cena zid="_107" waluta="USD">11.7</Cena>
               </Ceny>
            </Album>
         </Albumy>
      </Gatunek-muzyki>
      <Gatunek-muzyki zid="_108">
         <Nazwa zid="_109">ROCK</Nazwa>
         <Albumy zid="_110">
            <Album zid="_111" Nazwa-albumu="Foo Fighters">
               <Zespół zid="_112" Wykonawca="Foo Fighters">
                  <Członkowie zid="_113">
                     <Członek zid="_114">
                        <Imię-i-nazwisko zid="_115">Dave Grohl</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_116">
                        <Imię-i-nazwisko zid="_117">Nate Mendel</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_118">
                        <Imię-i-nazwisko zid="_119">Pat Smear</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_120">
                        <Imię-i-nazwisko zid="_121">Taylor Hawkins</Imię-i-nazwisko>
                     </Członek>
                     <Członek zid="_122">
                        <Imię-i-nazwisko zid="_123">Chris Shiflett</Imię-i-nazwisko>
                     </Członek>
                  </Członkowie>
               </Zespół>
               <Data-wydania zid="_124" dzień="7" miesiąc="lipca" rok="1995"/>
               <Nagradzana zid="_125" nagroda="ZłotaPłyta"/>
               <Ceny zid="_126">
                  <Cena zid="_127" waluta="PLN">30.99</Cena>
                  <Cena zid="_128" waluta="USD">10.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_129" Nazwa-albumu="Sonic Highways">
               <Zespół refzid="_112"/>
               <Data-wydania zid="_130" dzień="10" miesiąc="listopada" rok="2014"/>
               <Nagradzana zid="_131" nagroda="ZłotaPłyta"/>
               <Ceny zid="_132">
                  <Cena zid="_133" waluta="PLN">32.99</Cena>
                  <Cena zid="_134" waluta="USD">12.99</Cena>
               </Ceny>
            </Album>
            <Album zid="_135" Nazwa-albumu="Concrete and Gold">
               <Zespół refzid="_112"/>
               <Data-wydania zid="_136" dzień="15" miesiąc="września" rok="2017"/>
               <Nagradzana zid="_137" nagroda="ZłotaPłyta"/>
               <Ceny zid="_138">
                  <Cena zid="_139" waluta="PLN">31.99</Cena>
                  <Cena zid="_140" waluta="USD">11.99</Cena>
               </Ceny>
            </Album>
